//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireSafety
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FireSafetyEntities : DbContext
    {
        public FireSafetyEntities()
            : base("name=FireSafetyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FPO_0_Klas> FPO_0_Klas { get; set; }
        public virtual DbSet<FPO_1_Klas> FPO_1_Klas { get; set; }
        public virtual DbSet<FPO_2_Klas> FPO_2_Klas { get; set; }
        public virtual DbSet<FPO_3_Klas> FPO_3_Klas { get; set; }
        public virtual DbSet<FPO_4_Klas> FPO_4_Klas { get; set; }
        public virtual DbSet<FPO_5_Klas> FPO_5_Klas { get; set; }
        public virtual DbSet<Object> Objects { get; set; }
        public virtual DbSet<OFP_Limit_Values> OFP_Limit_Values { get; set; }
        public virtual DbSet<Start_Conditions> Start_Conditions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
