//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireSafety
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPO_5_Klas
    {
        public int Id_FPO_5 { get; set; }
        public string Room_Func { get; set; }
        public double Low_combustion { get; set; }
        public double Fire_Speed { get; set; }
        public double Burn_Speed { get; set; }
        public double Generate_Smoke { get; set; }
        public double Сonsumption_O2 { get; set; }
        public double Selection_СО2 { get; set; }
        public double Selection_СО { get; set; }
        public double Selection_HCL { get; set; }
        public Nullable<int> Id_Limit { get; set; }
        public Nullable<int> Id_Object { get; set; }
        public Nullable<int> Id_Conditions { get; set; }
    }
}
