//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireSafety
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public int Id_Object { get; set; }
        public string Adress_object1 { get; set; }
        public string Type_house { get; set; }
        public string Room_Func_object { get; set; }
        public double Area_object { get; set; }
        public double Volume_object { get; set; }
        public double Volume_free_object { get; set; }
        public double Heihgt__object { get; set; }
        public string Z_object { get; set; }
        public string B_object { get; set; }
        public string A_object { get; set; }
        public string t_крТ { get; set; }
        public string t_крPV { get; set; }
        public string t_крO2 { get; set; }
        public string t_крТCO2 { get; set; }
        public string t_крCO { get; set; }
        public string t_крHCL { get; set; }
        public string Сonclusion { get; set; }
        public string t_кр { get; set; }
        public string t_нб { get; set; }
        public Nullable<int> Id_FPO_5 { get; set; }
        public Nullable<int> Id_FPO_4 { get; set; }
        public Nullable<int> Id_FPO_3 { get; set; }
        public Nullable<int> Id_FPO_2 { get; set; }
        public Nullable<int> Id_FPO_1 { get; set; }
        public Nullable<int> Id_FPO_0 { get; set; }
    }
}
