//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireSafety
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFP_Limit_Values
    {
        public int Id_Limit { get; set; }
        public double Temperature { get; set; }
        public double Oxygen_Density { get; set; }
        public double CO_Density { get; set; }
        public double CO2_Density { get; set; }
        public double HCL_Density { get; set; }
        public double Optical_Density { get; set; }
        public Nullable<int> Id_FPO_0 { get; set; }
        public Nullable<int> Id_FPO_1 { get; set; }
        public Nullable<int> Id_FPO_2 { get; set; }
        public Nullable<int> Id_FPO_3 { get; set; }
        public Nullable<int> Id_FPO_4 { get; set; }
        public Nullable<int> Id_FPO_5 { get; set; }
    }
}
