//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireSafety
{
    using System;
    using System.Collections.Generic;
    
    public partial class Start_Conditions
    {
        public int Id_Conditions { get; set; }
        public double Start_Ligting { get; set; }
        public double Start_Temperature { get; set; }
        public double Specific_Isobaric { get; set; }
        public double Partial_Density { get; set; }
        public Nullable<int> Id_FPO_0 { get; set; }
        public Nullable<int> Id_FPO_1 { get; set; }
        public Nullable<int> Id_FPO_2 { get; set; }
        public Nullable<int> Id_FPO_3 { get; set; }
        public Nullable<int> Id_FPO_4 { get; set; }
        public Nullable<int> Id_FPO_5 { get; set; }
    }
}
